### ISSUE TITLE
BOT Scripts (W.I.P) 

### ISSUE THREAD

**Issue by Koriebonx98** [Joelrau/iw7-mod#100]
https://github.com/DoktorSAS/GSC/issues/10

The amazing @DoktorSAS has scripts for other call of duty mod clients, So i have asked him to do one for IW7-mod for us to have a functioning system for multiplayer
##########################################################################################

Concept is 
#########################################
Start match:
Wait for min of 1 player to connect & auto assign team 
Spawn bots & balance players
Rank system enabled 
#########################################

#########################################
Difficulty system if possible:
Ability to change bot size
Ability to change bot difficulty 
Bot difficulty algirhyme where it uses a mix of player level and performance based of last few matches
###########################################################################

###################################################
so e.g 
player levels
1-19 = Easy
20-35 = Normal
36 - 55+ = above normal or mix
#####################################

######################################
Performance based of KD Ratio from 3 matches:
0.5 or less = Easy
0.6  to 1.0 = Normal
1.1 - 1.5 = above normal
1.6 or above = above normal or Mix 
##########################

############
Bot Difficulty:
Be more responsive (aim bot) but not like hackers
More Health if bot difficulty is above normal
Faster Speed for harder diifficulty, slower speed for easy 
###########################################

Bot System should then theory be by default a challenging way to level up like the newer cod titles while also having options to modify to how each user likes aka Dedi 

If anyone has any other essential ideas to help please comment bellow with what else the script should do for Multiplayer Bots

**Comment by DoktorSAS** [comment]
Since its GSC its not client related so this post its not an issue related to the client. 
If the GSC load and with GSC we catch any issue we will report it as intended.

This issue can be closed and [Koriebonx98](https://github.com/Koriebonx98) on how to open issue related to the client if we find any.
