### ISSUE TITLE
Instruction Menu

### ISSUE THREAD

**Issue by Matiasm500** [Joelrau/iw7-mod#104]
Is it possible to do an Instruction Menu to edit game settings like BOIII?

![Captura de pantalla 2024-01-22 214114](https://github.com/Joelrau/iw7-mod/assets/96822329/6d1fdd4b-0b39-41d0-9029-9f9095c095d5)
![Captura de pantalla (3)](https://github.com/Joelrau/iw7-mod/assets/96822329/a466fb96-e5a2-456f-86e1-9a6c45cb8bc0)
![Captura de pantalla (4)](https://github.com/Joelrau/iw7-mod/assets/96822329/b9c9f38f-136e-4284-94d8-6276b4b7fa3d)

**Comment by vos6434** [comment]
Instruction Menu?

**Comment by mjkzy** [comment]
game options are already supported im sure...

**Comment by Matiasm500** [comment]
> Instruction Menu?

Sorry, I had the game in another language. The menu's name in english is Combat Training

**Comment by Matiasm500** [comment]
> game options are already supported im sure...

Sorry. I meant game rules in the public match

**Comment by Matiasm500** [comment]
![image](https://github.com/Joelrau/iw7-mod/assets/96822329/a3608a37-3878-48b9-95b3-daca9ec74833)

**Comment by Matiasm500** [comment]
With Combat Training in BOIII you can edit a game like a custom games but when you start the match you can level up with bots

**Comment by mjkzy** [comment]
combat training will probably be added soon by the guy who usually does it. just give us some time please, we aren't released yet.

**Comment by Matiasm500** [comment]
Ok don't worry. Thanks for all the job you do
