### ISSUE TITLE
Playercard reset and "disconnect" command crash

### ISSUE THREAD

**Issue by TheNineBreaker** [Joelrau/iw7-mod#107]
Its a minor issue, but playercard background and icon always reset after one or two matches in multiplayer. I hope it can be fixed somehow. Also the game do nothing when you choose "leave match" in multiplayer, and if "disconnect" command used, it crashes for some reason. 
Thanks for working on this project. 

UPD: The game also crashes without errors or creating dump file at random. Never happened with old versions.

**Comment by mjkzy** [comment]
we dont support playercard stuff officially yet. also, disconnect and such works on my end. closing for now as its working for everyone else but if you have a minidump, send the text file here

**Comment by TheNineBreaker** [comment]
Well there is 2 text files. I send both.
[crash.dmp](https://github.com/Joelrau/iw7-mod/files/14069215/crash.dmp)
[info.txt](https://github.com/Joelrau/iw7-mod/files/14069219/info.txt)
Thats from disconnect crash.
Thanks for clarifying about playercard. You doing God's work, i wish you to complete this project without much problems.
