### ISSUE TITLE
Possible issue when translating through Wine

### ISSUE THREAD

**Issue by ComoSgt** [Joelrau/iw7-mod#11]
I'm experimenting with the mod on Linux, specifically on the Steam Deck through Bottles, and I'm unsure whether or not it's a translation issue or other compatibility issue, but whenever I load up the mod, the splash screen does not render correctly and the program never launches. When I disable the splash screen and launch the program again, it brings up doesn't start at all or brings up the following error;

Fatal error (0xC0000005) at 0x0000000014BC0D657
The thread tried to read from or write to a virtual address for which it does not have the appropriate access.

I'm unsure if I'm missing some sort of dependency in the sandbox or something along those lines. The error came up once or twice when first starting it up on Windows but it's been working perfectly fine since than. This issue only comes up when trying to run it through Wine on Linux.

**Comment by ujicos** [comment]
Have you tried to run the steam version of the game first to see compatibility?

**Comment by ComoSgt** [comment]
The game works just fine through steam from my own testing, it passes every check, it's even verified. The issues come up when trying to use the exe that gets built when compiling the project, " iw7-mod.exe". I can't seem to figure out the source of the error, if you try this, you need to disable the splash screen as it appears to cause a visual bug that then causes the exe to hang. After that the game will at least attempt to boot but the error than comes up. I've tested the exe with a disabled splash screen on windows as well and the issue did not occur so it seems to be an issue with either the way wine is translating it or something within the code that wine is failing to pick up on or something. There's nothing wrong with the code since I'm using it for an unintended purpose and I don't expect this to be a big issue as it's not, I'm just testing out of curiosity

**Comment by phaon1** [comment]
> this issue is already known, the current function that automatically detects steam installation path works only for windows as it searches the windows registery of the steam path and load the additional steam stuff, so we made it in h1-mod that you put steam installation path yourself and like that you can launch the game with no problems.

so there is currently no way to do this here?

**Comment by skkuull** [comment]
> so there is currently no way to do this here?

could be, in the future.

**Comment by skkuull** [comment]
@ComoSgt @phaon1 i might need a tester for this, if you're interested msg me on discord: Skull#0185

**Comment by JHansen13** [comment]
Did anything ever come of this? I am less versed in Linux than ComoSgt, but would love to get this going on steam deck. Let me know if I can help
