### ISSUE TITLE
servers?

### ISSUE THREAD

**Issue by Koriebonx98** [Joelrau/iw7-mod#115]
when trying to host a server for either mp or zm it says some scripts failed to decomy or something?

**Comment by TacTicTow** [comment]
I got my server online and running and can even query it, when I go to connect I am disconnected almost immediately and when i look at the console of the server this is what I see

*********** script runtime error *************
while processing instruction OP_equality
        at function "givecontractchallenge" in file "scripts/mp/contracts.gsc"
        at function "onplayerconnect" in file "scripts/mp/contracts.gsc"
**********************************************
*********** script runtime error *************
while processing instruction OP_JumpOnTrueExpr
        at function "givecontractchallenge" in file "scripts/mp/contracts.gsc"
        at function "onplayerconnect" in file "scripts/mp/contracts.gsc"
**********************************************
*********** script runtime error *************
while processing instruction OP_equality
        at function "givecontractchallenge" in file "scripts/mp/contracts.gsc"
        at function "onplayerconnect" in file "scripts/mp/contracts.gsc"
**********************************************
*********** script runtime error *************
while processing instruction OP_CastBool
        at function "givecontractchallenge" in file "scripts/mp/contracts.gsc"
        at function "onplayerconnect" in file "scripts/mp/contracts.gsc"
**********************************************
*********** script runtime error *************
while processing instruction OP_CastBool
        at function "givecontractchallenge" in file "scripts/mp/contracts.gsc"
        at function "onplayerconnect" in file "scripts/mp/contracts.gsc"
**********************************************
*********** script runtime error *************
while processing instruction OP_JumpOnFalse
        at function "givecontractchallenge" in file "scripts/mp/contracts.gsc"
        at function "onplayerconnect" in file "scripts/mp/contracts.gsc"
**********************************************
*********** script runtime error *************
while processing instruction OP_equality
        at function "givecontractchallenge" in file "scripts/mp/contracts.gsc"
        at function "onplayerconnect" in file "scripts/mp/contracts.gsc"
**********************************************
*********** script runtime error *************
while processing instruction OP_JumpOnTrueExpr
        at function "givecontractchallenge" in file "scripts/mp/contracts.gsc"
        at function "onplayerconnect" in file "scripts/mp/contracts.gsc"
**********************************************
*********** script runtime error *************
while processing instruction OP_equality
        at function "givecontractchallenge" in file "scripts/mp/contracts.gsc"
        at function "onplayerconnect" in file "scripts/mp/contracts.gsc"
**********************************************
*********** script runtime error *************
while processing instruction OP_CastBool
        at function "givecontractchallenge" in file "scripts/mp/contracts.gsc"
        at function "onplayerconnect" in file "scripts/mp/contracts.gsc"
**********************************************
*********** script runtime error *************
while processing instruction OP_CastBool
        at function "givecontractchallenge" in file "scripts/mp/contracts.gsc"
        at function "onplayerconnect" in file "scripts/mp/contracts.gsc"
**********************************************
*********** script runtime error *************
while processing instruction OP_JumpOnFalse
        at function "givecontractchallenge" in file "scripts/mp/contracts.gsc"
        at function "onplayerconnect" in file "scripts/mp/contracts.gsc"
**********************************************

**Comment by TacTicTow** [comment]
[http://sb.hosted.nfoservers.com/e107_plugins/lgsl/?s=10](url)
