### ISSUE TITLE
Fed,,,,,,

### ISSUE THREAD

**Issue by GT4nMore** [Joelrau/iw7-mod#116]
![image](https://github.com/Joelrau/iw7-mod/assets/71804090/02a40d9b-3128-466f-bb1d-0e846f610892)
Excuse me fed, I downloiad install link .zip folderDonate to Federica Cecchettoicon using operagz and put it into my game. It not qork and jzip opening? how?
Hallo from Lidls!
Much Love xoxox,

**Comment by Chopper1337** [comment]
sirs,, I am having issues same !! meybe it is comon?
![image](https://github.com/Joelrau/iw7-mod/assets/43015696/fa5794c1-a42f-4496-a67d-6526f2835680)

**Comment by NotTofumi** [comment]
![image](https://github.com/Joelrau/iw7-mod/assets/90161773/6f12fcfd-0f9f-401c-b277-6eae39344b03)

Henlo misters, I see ver comon issu. I no git work. ply hlp

**Comment by mjkzy** [comment]
ez fix
