### ISSUE TITLE
Selecting the store gets you stuck

### ISSUE THREAD

**Issue by Arnauw** [Joelrau/iw7-mod#15]
When selecting the store the game gets stuck in an infinite loop while "fetching info", forcing you to alt F4 to quit the game.

**Comment by skkuull** [comment]
this could be easily fixed if lui-scripting will be a thing in future.

**Comment by Lierrmm** [comment]
Store can be disabled by setting the DVAR `killswitch_store` to 1. It will also remove it from the menu.

Example with killswitch_store set to 0
![image](https://user-images.githubusercontent.com/13552261/218529272-46df611a-2a40-4017-aace-a25189675115.png)


Example with killswitch_store set to 1
![image](https://user-images.githubusercontent.com/13552261/218529334-4a6ec56c-eb35-42b6-bd77-7044e2b67b74.png)

Not sure if it should be forced to 1 - as you can still get to quartermaster through public match > quartermaster
