### ISSUE TITLE
Fix team based game modes for online bot matches 

### ISSUE THREAD

**Issue by WantedDV** [Joelrau/iw7-mod#18]
It is now possible to rank up with bots in public matches using the command `xblive_privatematch 1;xpartygo;xblive_privatematch 0` to start the match.

It works for games like "Free for All" and "Gun Game" but not for any team based modes like TDM and DOM. In team based modes it appears that lobby is filled with bots before the player get assigned to a team, and with no place left for the player so they just get sent back to the lobby.

I would imagine that the fix for this would be to assign the player to a team before the bots connect. Either:
- ~~add a delay for bots to spawn in~~
- ~~wait for the player to spawn in then fill~~
- assign a team in the lobby before the game even starts

OR find an alternative way to start the game that actually initiates the countdown procedure.

**Comment by ZNicksonZ343** [comment]
So... the TDM problem was fixed?

**Comment by Ston3Cold** [comment]
> So... the TDM problem was fixed?

Well, hooking the disable host migration dvar does result in the game not kicking you back to the lobby, but then you as the player, does not get assigned to a team. This causes some issues with the hud and you cannot identifiy team mate from foe.

So we're halfway there, but need to find a way to force assign the player to a team too, to solve the hud issues.

**Comment by ZNicksonZ343** [comment]
I will install the game to write down possible solutions

**Comment by ZNicksonZ343** [comment]
I started a match and setted 'xblive_privatematch 0' but then I couldn't spawn the bots

**Comment by Ston3Cold** [comment]
> I started a match and setted 'xblive_privatematch 0' but then I couldn't spawn the bots. I think the 'spawnbot' dvar is missing or something

You must type:

xblive_privatematch 1;xpartygo;xblive_privatematch 0

Once the lvl has completed loading, while the camera is panning, you must type xblive_privatematch 1 again, otherwise it will kick you out.

If done in time, you can choose your loadout and start playing.

**Comment by ZNicksonZ343** [comment]
Alright, thanks man

**Comment by Koriebonx98** [comment]
Is there away to make this into a script? 

So when player loads up then exec the command/script?
