### ISSUE TITLE
Unlocking directors cut

### ISSUE THREAD

**Issue by phaon1** [Joelrau/iw7-mod#20]
I played through all the ees using this mod and unlocked directors cut and save the iw7-mod folder data assuming this would contain my progress and would be transferable but it wasn't and I lost all my progress reinstalling Windows. Is there any way to unlock directors cut again without going through the painful process of doing all the easter eggs again

**Comment by skkuull** [comment]
I added an experimental command regards to it for now, command usage is `director_cut 1/0`
