### ISSUE TITLE
Strange permenantely stunned glitch

### ISSUE THREAD

**Issue by phaon1** [Joelrau/iw7-mod#22]
If God mode is enabled and you receive any stun or explosive damage you become permanently stunned and are unable to run or move at normal walk speed. I have only tested this in zombies unsure it it happens in other modes. Both disabling god mode and being revived don't fix this. The only way to fix it i can see is to end the match and start another one

**Comment by Joelrau** [comment]
try this again with the latest build, should have been related to the g_speed patch
