### ISSUE TITLE
Build issue?

### ISSUE THREAD

**Issue by Aprutey** [Joelrau/iw7-mod#28]
I followed instruction to build but it throws this error and says build failed

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "pushd ..
tools\premake5 generate-buildinfo
popd
:VCEnd" exited with code 1.	client	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	147	
![s](https://user-images.githubusercontent.com/125611517/219495157-2c098ecd-f8bc-4afb-b8ee-53b689cb5569.PNG)

**Comment by Aprutey** [comment]
I did? using vs 2022 i clicked File > Clone Repository> link  i used https://github.com/Joelrau/iw7-mod.git
i get the files Click Generate.bat and it then creates build file and i open iw7-mod.sln i try to build in vs it says  build failed

**Comment by skkuull** [comment]
Do you have https://git-scm.com/ installed? if not just install it

**Comment by Aprutey** [comment]
It works with installing that but when i try launch iw7-mod it says:
![s](https://user-images.githubusercontent.com/125611517/220448982-28a59a63-9847-4d87-bf59-c7e9401f9780.PNG)

**Comment by Joelrau** [comment]
repacks are not supported.

**Comment by Aprutey** [comment]
I own the game? I verified the integrity of  IW now I got a step closer and it now says i give up lol
![s](https://user-images.githubusercontent.com/125611517/220608081-4ae45d60-d4e2-4750-bfdf-3f76ef7554b3.PNG)

**Comment by Aprutey** [comment]
I was using a patch mod so i will just reinstall the entire game and try again and see if that works

**Comment by skkuull** [comment]
> I own the game? I verified the integrity of IW now I got a step closer and it now says i give up lol ![s](https://user-images.githubusercontent.com/125611517/220608081-4ae45d60-d4e2-4750-bfdf-3f76ef7554b3.PNG)

your files already explains that you don't own the game lmfao

**Comment by belloumi-hamza** [comment]
then make them supported.

**Comment by skkuull** [comment]
nope we wont you need to buy it, even though you'll not able to launch the game till you own it on steam
