### ISSUE TITLE
[Arxan] Patch Integrity checks

### ISSUE THREAD

**Issue by Joelrau** [Joelrau/iw7-mod#3]
Hooking currently will cause the game to crash.

**Comment by Spidermanagent** [comment]
use undetected ce https://www.unknowncheats.me/forum/call-of-duty-modern-warfare/500422-undetected-cheat-engine.html

**Comment by shit-ware** [comment]
What the hell are you talking about @Spidermanagent

**Comment by skkuull** [comment]
> What the hell are you talking about @Spidermanagent

fr

**Comment by CrazyCSIW6** [comment]
dumbass legit thinks its a cheat lmao 💀

**Comment by Javilillo30** [comment]
hello when you can get iw7 is that I really want to play it

**Comment by skkuull** [comment]
> hello when you can get iw7 is that I really want to play it

Still very early in development.

**Comment by Spidermanagent** [comment]
Why is no one updating this repo? Is the project still alive?

**Comment by ujicos** [comment]
Does this project load past "Connecting to online services", or is that part of an integrity check we need to create first?

**Comment by Joelrau** [comment]
> Does this project load past "Connecting to online services", or is that part of an integrity check we need to create first?

Needs integrity checks patched for that.

**Comment by Joelrau** [comment]
https://github.com/momo5502/boiii
