### ISSUE TITLE
Command list with the most Important commands 

### ISSUE THREAD

**Issue by Kakarot1908** [Joelrau/iw7-mod#32]
I’ve been trying a lot but I can’t find out how certain functions work like UA or at least adding bots to a private match to rank up

**Comment by Ston3Cold** [comment]
See this existing issue for commands on how to start a bot match via the public playlists:

https://github.com/Joelrau/iw7-mod/issues/18

It only works for FFA and Gungame, team modes not working unfortunately.

**Comment by Kakarot1908** [comment]
> 

Hey thanks for the reply I did manage to get it work but sadly unless I go into a private match and type in “Bot_autoconnect_default 1” then going out and putting in the the other command bots won’t auto fill and I have to do that everytime the round ends

**Comment by Kakarot1908** [comment]
> you can try searching for dvars like `scr_war_...`, where `war` stands for tdm. There are a set of commands for each gametype.

Didn’t really work seems like there’s no way it’s just incredibly annoying to keep on going into a match using the command so Bots join and then reentering one

**Comment by Ston3Cold** [comment]
I'll play around too with the cmds to see if there is a way increase the score limits. Dedicated servers work in the latest build, but sadly it seems that one can't spawn bots yet and obviously dedi's are essentially private matches with ranking disabled. Here's hoping the devs add support for bots and ranking soon on dedi's too :)
