### ISSUE TITLE
I can't start a match afte update iw7-mod.exe

### ISSUE THREAD

**Issue by Matiasm500** [Joelrau/iw7-mod#33]
After I updated the iw7 mod I can´t start a private match or zombies.
And now I can´t use this command:
xblive_privatematch 1;xpartygo;xblive_privatematch 0

**Comment by UndeadFrankie** [comment]
have you tried using: devmap cp_zmb? 
I didn't have any issues starting a game after the unlockall update.

**Comment by Matiasm500** [comment]
![image](https://user-images.githubusercontent.com/96822329/226133510-a27b8e1b-aff6-4bb2-8278-5b18f8397f91.png)
Its infinite loading

**Comment by Matiasm500** [comment]
![Captura de pantalla (9)](https://user-images.githubusercontent.com/96822329/226133545-9a74363a-b873-4a93-ad15-6401cd9c284c.png)
And this is with the older version
