### ISSUE TITLE
where can i find the unlock all command and how to get rank 999

### ISSUE THREAD

**Issue by kixz1ra** [Joelrau/iw7-mod#39]

**Comment by Minni23** [comment]
1) cg_unlockall_items  
2) cg_unlockall_loot 
3) unlockstats

**Comment by kixz1ra** [comment]
> 1. cg_unlockall_items
> 2. cg_unlockall_loot
> 3. unlockstats

do i need to put this in console?
bc when i put it in console nothing works

**Comment by ItsJustAK** [comment]
> 

Does not work, at least for me

**Comment by mojerm** [comment]
it also doesn't work for me
