### ISSUE TITLE
I can't clone the repo...

### ISSUE THREAD

**Issue by MattKlay** [Joelrau/iw7-mod#41]
I tried with GitHub Desktop and even with GitHub CLI, but it says always _This folder contains files. Git can only clone to empty folders._

**Comment by ujicos** [comment]
The issue is literally in the error.
Make sure the folder you are trying to clone to has nothing in it. A good way to do this is to NOT make a folder, let the desktop app make the folder for you (in this case im sure you have to rename the folder)

**Comment by diamante0018** [comment]
SKILL ISSUE

**Comment by mjkzy** [comment]
lol
