### ISSUE TITLE
I have no clue how to install this

### ISSUE THREAD

**Issue by DONPOPACAPO** [Joelrau/iw7-mod#44]
I have downloaded the iw7 mod clone successfully but i have no idea how to install the mod, if i had a tutorial that would be pretty cool.

**Comment by blitzkrieg99** [comment]
Have you already compiled the client from source?

**Comment by DONPOPACAPO** [comment]
Yes

**Comment by herrblitzkrieg** [comment]
Then go to 'iw7-mod\build\bin\x64\Debug' and copy 'iw7-mod.exe', 'runner.exe' and 'tlsdll.dll' to 'C:\Program Files (x86)\Steam\steamapps\common\Call of Duty - Infinite Warfare'. Double-click 'iw7-mod.exe'.

**Comment by DONPOPACAPO** [comment]
My iw7-mod doesn't have an iw7-mod.exe i only have an sln.

**Comment by herrblitzkrieg** [comment]
Then you haven't compiled from source yet.

Follow the instructions already explained in a duplicate issue: https://github.com/Joelrau/iw7-mod/issues/25#issuecomment-1427887477

**Comment by DONPOPACAPO** [comment]
Tysm this was really helpful. (btw people reading this, press the build client button in the build drop-down menu really confused the hell out of me.)

**Comment by Entelechies** [comment]
After I generate the .bat file, I open the iw7-mod.sln file and can not find where to build this file to fully compile the build. Any help?

**Comment by herrblitzkrieg** [comment]
> After I generate the .bat file, I open the iw7-mod.sln file and can not find where to build this file to fully compile the build. Any help?

How to build/compile? Read the messages above yours, alternatively you can press F7 to build solution.

**Comment by Entelechies** [comment]
@herrblitzkrieg Ive tried pressing F7 while the sln file is open but it does not seem to do anything. When I try and go to terminal and try "run build task" it says that the terminal process failed to launch and the build failed.
![VS](https://github.com/Joelrau/iw7-mod/assets/129815885/d5695d14-c073-481d-8991-844adb4125e8)

**Comment by herrblitzkrieg** [comment]
> @herrblitzkrieg Ive tried pressing F7 while the sln file is open but it does not seem to do anything. When I try and go to terminal and try "run build task" it says that the terminal process failed to launch and the build failed. ![VS](https://user-images.githubusercontent.com/129815885/239659660-d5695d14-c073-481d-8991-844adb4125e8.png)

Are you using Visual Studio Code? Wrong.

Use [Visual Studio](https://visualstudio.microsoft.com/) (Community 2022). Everything else is already explained in https://github.com/Joelrau/iw7-mod/issues/25#issuecomment-1427887477

**Comment by Entelechies** [comment]
@herrblitzkrieg I appreciate your help. Running it with Visual Studio Code Community Edition did the trick.

**Comment by Adams2074** [comment]
hi guys i have a problem with building files. i don't know what I'm doing right now but after building a file I have in debug only runner.exe. i don't have iw7-mod.exe or anything like this.

![Zrzut ekranu 2023-05-22 225517](https://github.com/Joelrau/iw7-mod/assets/132617832/6577fe82-86cf-4301-bdb8-61fae8cb906c)

**Comment by xhibition** [comment]
> hi guys i have a problem with building files. i don't know what I'm doing right now but after building a file I have in debug only runner.exe. i don't have iw7-mod.exe or anything like this.
> 
> ![Zrzut ekranu 2023-05-22 225517](https://user-images.githubusercontent.com/132617832/240040188-6577fe82-86cf-4301-bdb8-61fae8cb906c.png)

![image](https://github.com/Joelrau/iw7-mod/assets/134362002/72024544-b081-43a3-8714-c0024c21df26)


I have a suspicion these two errors could be contributing to the lack of our IW7.exe's. But I'm clueless so don't take my suggestion as verbatim. I'm indeed having the same issues, I've followed Ethan's little guide to a tee; cloned from the repo via the green code button, ran the generate.bat, built the Client and even the entire solution itself and always getting these two little errors.

**Comment by Adams2074** [comment]
Me too m8 idk what I have to do now... after installing community studio I don't even have runner.exe

**Comment by herrblitzkrieg** [comment]
> I FOUND IT. i reinstalled visual studio community 2022 but with that i installed everything on pics here. after that i choosed debug on top and clicked build solution (or something like that its first after u click on the build list sorry i have that in polish sorry) with that i finally got everything right

In fact, you can also just modify your current Visual Studio installation by simply running the Visual Studio Installer once again and select/deselect Visual Studio components you want to add/remove.

![83925783295683256](https://github.com/Joelrau/iw7-mod/assets/65146766/c309df35-aba0-43fb-a899-e5a9dfa936b2)

It's enough to only select **Desktop development with C++**.

**Comment by xhibition** [comment]
> > > I FOUND IT. i reinstalled visual studio community 2022 but with that i installed everything on pics here. after that i choosed debug on top and clicked build solution (or something like that its first after u click on the build list sorry i have that in polish sorry) with that i finally got everything right
> > 
> > 
> > In fact, you can also just modify your current Visual Studio installation by simply running the Visual Studio Installer once again and select/deselect Visual Studio components you want to add/remove.
> > ![83925783295683256](https://user-images.githubusercontent.com/65146766/240319611-c309df35-aba0-43fb-a899-e5a9dfa936b2.png)
> > It's enough to only select **Desktop development with C++**.
> 
> ![image](https://user-images.githubusercontent.com/134362002/240356323-a152aa3d-86e8-4962-88fc-fc6baa7caea1.png)
> 
> I've completely reinstalled Visual Studio with the suggested options regarding installation and still getting the same errors, absolutely no idea what I'm doing wrong :/

So I've fixed my issue thanks to a friend helping me out.
He figured out that the errors I was getting were a clone issue. To get around this, we used Git to clone the repository properly.
This is what happened; when we ran the generate.bat it wasn't installing the submodules, so using Git we used the following command "git clone https://github.com/Joelrau/iw7-mod.git" it successfully installed the submodules. Thereafter, we cleaned the build within the solution before building it and now everything works properly.

If anyone are having issues try this, it might work for you too.
