### ISSUE TITLE
Minidump error after starting cutscene 

### ISSUE THREAD

**Issue by CCLA1903** [Joelrau/iw7-mod#46]
![image](https://user-images.githubusercontent.com/132507011/236041603-28f29b25-7f2e-4acc-bf45-c0d9e5e6bf82.png)
[boiii-crash-2023-05-03-15-25-21.zip](https://github.com/Joelrau/iw7-mod/files/11390978/boiii-crash-2023-05-03-15-25-21.zip)

**Comment by An0mal0us** [comment]
You able to find a fix cause I have the same problem

**Comment by CCLA1903** [comment]
Got a new pc 💀

**Comment by An0mal0us** [comment]
and it worked?

**Comment by CCLA1903** [comment]
Yep
Sorry I tried for months and no one was able to help. By then I needed a
new pc and I was oh yeah let me try that again worked first try

**Comment by An0mal0us** [comment]
yh they don't reply at all, Imma just try anything

**Comment by CCLA1903** [comment]
Only thing I didn’t try was a new install of windows… I’d recommend that
last and if possible make a backup first saves a lot of time for all your
apps   New pc had problems at the start had to reinstall windows like 8
times 🥲

**Comment by An0mal0us** [comment]
8 times goddddd damn

**Comment by CCLA1903** [comment]
New hardware new problems 🥲

**Comment by An0mal0us** [comment]
Imma just try a few things to fix it

**Comment by An0mal0us** [comment]
![Screenshot 2023-07-09 20-10-54](https://github.com/Joelrau/iw7-mod/assets/108438235/2133e17d-b7d3-4486-939c-76bb38900bad)
Yh this is what I get all the time
