### ISSUE TITLE
David Hasselhoff cannot be used after making the spaceland easter egg.

### ISSUE THREAD

**Issue by OctavioxD115** [Joelrau/iw7-mod#47]
I tell you that I finished making the Easter egg, and when I came out it wouldn't let me play with David, I made the Easter egg with my brother and my brother if he lets it and when I try it doesn't work for me ¿do you think you can add a command to play with the special characters on each map?

**Comment by OctavioxD115** [comment]
Update: When I go to barracks, it does not appear to me that I had done the ee of spaceland
![image](https://github.com/Joelrau/iw7-mod/assets/109006655/94b3e333-1793-4bfa-990a-cfe0ab9d0d82)

**Comment by mjkzy** [comment]
this *should* be fixed now but if not, plz lmk. i think the old `director_cut` command was messing with stats
