### ISSUE TITLE
relock stats?

### ISSUE THREAD

**Issue by Mrpoostanky** [Joelrau/iw7-mod#49]
is there a way to reset your stats. i thought i could put myself at a specific level but now im stuck at level 999. is there a way to get specific stats or to just reset them?

**Comment by Mrpoostanky** [comment]
so i relocked my stats but im still wondering if theres a way to get to a specific level

**Comment by Koriebonx98** [comment]
What I done is delete the player files, launched the game and then closed it down and relaunched it. That should work?

**Comment by mjkzy** [comment]
#102
