### ISSUE TITLE
unlock all tool aint working

### ISSUE THREAD

**Issue by Steevo8657** [Joelrau/iw7-mod#50]
every time i try the unlock all thing it doesnt work ive tried unlockstats, cg_mpWeaponUnlock, cg_unlockall_items 1, i click enter they just dont seem to work, could yall fix that

**Comment by herrblitzkrieg** [comment]
_"could yall fix that"..._ I suggest you deliver proof first that it is indeed a client issue cause I can verify all those commands work just fine. Unless someone else got the same issue...

**Comment by Steevo8657** [comment]
yeah many people after reading comments have same issue were  anything we type in the ~ command doesnt actually work in game
