### ISSUE TITLE
need iw ?

### ISSUE THREAD

**Issue by seraze9** [Joelrau/iw7-mod#52]
we have to get the game or not ?

**Comment by Ston3Cold** [comment]
> we have to get the game or not ?

Yes, you need a legit copy!

**Comment by Koriebonx98** [comment]
You need ownership of the legit game as they do steam check. However I’ve found out if you own the original game and not the zombie dlc, obtain the dlc files and put in game folder. When playing via steam the dlc’s work without purchase 🤨 

mother than that £40 for season pass, £50
For game but it’s on sale atm on steam
