### ISSUE TITLE
Unlock All Commands Not Working

### ISSUE THREAD

**Issue by Marshallplayz29** [Joelrau/iw7-mod#54]
Idk if its a game thing or im not doing it correct but ive tried every command in past issues and ones i thought would work and none of the unlock all commands show up in console or work even if i do it without console otherwise the launcher and shit work just fine

**Comment by OctavioxD115** [comment]
Commands: 
cg_unlockall_items 1
cg_unlockall_loot 1

**Comment by Steevo8657** [comment]
ive tried all of those and they dont work

**Comment by OctavioxD115** [comment]
and with 
Unlockstats
enable_unlock_sync 1 
try those

**Comment by OctavioxD115** [comment]
And for it to work, go to the menu and then enter the game mode that you are going to play

**Comment by Steevo8657** [comment]
Ive tried it, it still doesnt work
