### ISSUE TITLE
Fatal error memory 15 402

### ISSUE THREAD

**Issue by phantom2k22** [Joelrau/iw7-mod#56]
Hi, i download files  from RUI, run steam patch and then when i run iw7-mod.exe, I have a terminal that open, then the game launch with a black screen with "a37ae3a" written at the top, then all close and nothing

once i had in the terminal

Loading zone code_pre_gfx
Loading zone code_post_gfx
Loading zone ui_boot
Loading zone global
Loading zone common
Loading zone ui

then nothing happens

the console window continues, the black screen appears with the legend in the upper left margin and the game menu does not appear at all, What could be the failure or error?
PS: it also throws often fatal error memory 15 402
It's installed in E:\Call of Duty - Infinite Warfare

**Comment by Joelrau** [comment]
Buy the game on steam for this project to work.
