### ISSUE TITLE
DLC issue

### ISSUE THREAD

**Issue by Factivition** [Joelrau/iw7-mod#58]
i have dlc but not sure if its usable yet or if its corrupt in normal iw it works but in this it kicks me out saying dlc brokend or something like that....also how to i disable frags in mp bots are ridicilous with it lol

**Comment by Koriebonx98** [comment]
Try reevaluate with steam.
Cod cabin mod site is a good source for community and I’m sure it has some info about dlc

**Comment by herrblitzkrieg** [comment]
> also how to i disable frags in mp bots are ridicilous with it lol

Good question... right now my sorta workaround for this is using the [Trophy Drone](https://callofduty.fandom.com/wiki/Trophy_Drone) trait which keeps most of the incoming fatality frags in check. 😅
