### ISSUE TITLE
Servers 

### ISSUE THREAD

**Issue by Koriebonx98** [Joelrau/iw7-mod#62]
Not to sure what’s planned for the next version of iw7-mod

however to try help out, I’ve managed to sort the server side for zombies. I have a .bat to start the server, the map names and rotate eneabled. And works well

multiplayer, I got the files set up. Map rotation but can’t seem to get bots to spawn in 🤨 

I managed on the other cod clients to set a bat to start server, wait 10 secs, load mod client via batch with +connect (ip) to auto connect to the server on launch. But I’m struggling with this one

**Comment by ZNicksonZ343** [comment]
To spawn bots in multiplayer, you can try setting the dvar "bot_AutoConnectDefault 1" and restarting the map, but I don't know if this works for dedicated servers

**Comment by Koriebonx98** [comment]
I did see somewhere someone said about setting it to ranked, start game set to non ranked then spawn bits in or something… sounded complicated

**Comment by Koriebonx98** [comment]
the only result i get from it is bots that stay still.. possibly someone could write a script for it

**Comment by Ston3Cold** [comment]
> the only result i get from it is bots that stay still.. possibly someone could write a script for it

There is no gsc scripting support, so unless its ever implemented, good luck with that.

**Comment by Koriebonx98** [comment]
Hopefully be a new feature!! Then more can be possible

**Comment by Factivition** [comment]
@Koriebonx98 could i work on this with you? i have a pssoiblle fix send me link to the files

**Comment by Ston3Cold** [comment]
> @Koriebonx98 could i work on this with you? i have a pssoiblle fix send me link to the files

Would you mind sharing this possible fix of yours with me too? I assume it has to do with spawning of bots on a server? Could we perhaps chat on Discord?

**Comment by Koriebonx98** [comment]
im not a dev or anything. for zombies servers heres the !start_zm_server.bat stuff copy & paste into a text file and should be right structure 

@echo off
::///////////////////////////////////////////////////////////////////////
::///  	         iw7x Server Configuration start-up file	  		      ///
::///////////////////////////////////////////////////////////////////////
::// This config best view with Notepad++ or other non-windows notepad //
::///////////////////////////////////////////////////////////////////////
::// 	Your edited server.cfg in the "main" folder goes here  	       //
:://	This is were you edit your hostname, map & gamemodes from.     //
::///////////////////////////////////////////////////////////////////////

set ServerFilename=server_zm.cfg

::///////////////////////////////////////////////////////////////////////
:://You're done!! WARNING!!! Don't mess with anything below this line  //
::///////////////////////////////////////////////////////////////////////

set GAME_EXE=iw7-mod.exe
start %GAME_EXE% -dedicated +cpMode +set onlinegame 1 +set net_port "%port%" +exec %ServerFilename% +map_rotate

**Comment by Koriebonx98** [comment]
then put this in the iw7-mod folder as "server_zm.cfg"

and paste this into it

//////////////////////////////////////////////////
///          iw7x Server Configuration           //
//////////////////////////////////////////////////

//////////////////////////////////////////////////
// SERVER NAME & COLORS TIPS                    //
//////////////////////////////////////////////////
//                                              //
// ^1 Red                                       //
// ^2 Green                                     //
// ^3 Yellow                                    //
// ^4 Blue                                      //
// ^5 Cyan                                      //
// ^6 Pink                                      //
// ^7 White                                     //
// ^8 Depends on the team colors playing.       //
// ^9 Grey                                      //
// ^0 Black                                     //
// ^: Rainbow colors                            //
//                                              //
//////////////////////////////////////////////////

set sv_hostname "iw7 Default Server"            // Sets the server hostname.
set sv_motd ""                                  // Sets a custom motd which is shown on the intel message loadscreen when a player joins. Leave blank for default intel messages.

//////////////////////////////////////////////////
// ADMIN INFO (Optional)                        //
//////////////////////////////////////////////////

set _Admin ""                                   // Your username.
set _Email ""                                   // E-mail address. you can leave blank
set _Website ""                                 // Website. (IW4MAdmin uses this.)
set _Location "Earth"                           // Location

//////////////////////////////////////////////////
// NON-GAMEPLAY CONFIGURATION                   //
//////////////////////////////////////////////////

set party_maxplayers "4"                        // Max players in your server.
set rcon_password ""                            // Access to your server to change stuff remotely or ingame. (Empty = disabled)
set g_password ""                               // Password Protected Server. Leave blank if you want players to join or set password if you want to keep public out.
set sv_privateClients "0"                       // Maximum number of private clients allowed on the server (range 0-18 (clamped to sv_maxclients) )
set sv_privatePassword ""                       // Password for reserved slots. 
set sv_voice "2"                                // Server voice chat configuration ( 0 = "No Chat", 1 = "Free Chat", 2 = "Team Chat" (default) )
set g_allowVote "1"                             // Toggle voting for [player kick/map restart/next map] (0 or 1 (default) )
set g_deadChat "0"                              // Toggle allowing dead players to chat with living players (0 (default) or 1)
set g_inactivity "420"                          // Time in seconds before the server will kick a user for inactivity (range 0 - 10000)
set sv_kickBanTime "3600"                       // Time in seconds for a player temporary ban (on kick/tempban) (range 0 - 3600)
set sv_allowClientConsole "1"                   // Enable or Disable players ability to access server commands
set sv_timeout "60"                             // Timeout time period. You will timeout after (60) seconds when attempting to connect or if you are getting connection interruptions
set sv_reconnectlimit "3"                       // How many times you can try to reconnect
set sv_pure "1"                                 // verifying cilent files
set sv_floodProtect "1"                         // Chat Spam Protection
set sv_sayName "console"                        // name server-side 'say' commands show up as
set logfile "2"                                 // Enable loging 1-2? enable. 0 disable. Leave it on if you plan on using B3 or IW4MAdmin.
set g_logSync "1"                               // 1 always flush games_mp.log, 0 only flush on game end. Recommended to stay on for b3 and IW4MAdmin
set g_log "iw7-mod/logs/games_zm.log"               // Gamelog filename. If you edit this, Make sure you change B3.xml if you have bigbrotherbot. IW4MAdmin auto-detects however.


//////////////////////////////////////////////////
// EXO ZOMBIES GAMETYPE SETTINGS                //
//////////////////////////////////////////////////

set scr_zombies_scorelimit "0"                      // Target score before the round ends.
set scr_zombies_timelimit "0"                       // Duration in minutes for the game to end if the score limit isn't reached.
set scr_zombies_numlives "1"                        // Number of lives per player 0 for unlimited.
set scr_zombies_promode "0"

//////////////////////////////////////////////////////////
//               EXO ZOMBIE ROTATION LIST               //
//////////////////////////////////////////////////////////
//                                                      //
//          Rave in woods  -     cp_rave                //
//          Infection      -     cp_zmb                 //
//          Carrier        -     cp_disco               //
//          Descent        -     cp_final               //
//                         -     cp_town                //
//////////////////////////////////////////////////////////

set sv_maprotation "gametype zombies map cp_zmb map cp_rave map cp_final"

**Comment by Koriebonx98** [comment]
i have done multiplayer too but cant get bots working, here are the multiplayer stuff: save as !start_mp_server.bat" and paste this

@echo off
::///////////////////////////////////////////////////////////////////////
::///  	         S1x Server Configuration start-up file	  		      ///
::///////////////////////////////////////////////////////////////////////
::// This config best view with Notepad++ or other non-windows notepad //
::///////////////////////////////////////////////////////////////////////
::// 	Your edited server.cfg in the "main" folder goes here  	       //
:://	This is were you edit your hostname, map & gamemodes from.     //
::///////////////////////////////////////////////////////////////////////

set ServerFilename=server_mp.cfg`

::///////////////////////////////////////////////////////////////////////
:://You're done!! WARNING!!! Don't mess with anything below this line  //
::///////////////////////////////////////////////////////////////////////

set GAME_EXE=iw7-mod.exe
start %GAME_EXE% -dedicated +mpMode +set onlinegame 1 +set net_port "%port%" +exec %ServerFilename% +map_rotate +bot_AutoConnectDefault 1 +xpartygo +xblive_privatematch 0

**Comment by Koriebonx98** [comment]
this is the mp cfg for iw7, just copy and paste 

///////////////////////////////////////////////////
///         IW7x Server Configuration            //
///////////////////////////////////////////////////

///////////////////////////////////////////////////
// SERVER NAME & COLORS	TIPS                     //
///////////////////////////////////////////////////
//                                               //
// ^1 Red                                        //
// ^2 Green                                      //
// ^3 yellow                                     //
// ^4 Blue                                       //
// ^5 Cyan                                       //
// ^6 Pink                                       //
// ^7 White                                      //
// ^8 Depends on the team colors playing.        //
// ^9 grey                                       //
// ^0 Black                                      //
// ^: Rainbow colors                             //
//                                               //
///////////////////////////////////////////////////

set sv_hostname "IW6x Default Server"            // Sets the server hostname.
name "[IW6x] server"                             // Currently sets the say name

//////////////////////////////////////////////////
// ADMIN INFO (Optional)                        //
//////////////////////////////////////////////////

set _Admin ""                                   // Your username.
set _Email ""                                   // E-mail address. you can leave blank
set _Website ""                                 // Website. (IW4MAdmin uses this.)
set _Location "Earth"                           // Location

//////////////////////////////////////////////////
// NON-GAMEPLAY CONFIGURATION                   //
//////////////////////////////////////////////////

set sv_maxclients "18"                          // Max players in your server.
set rcon_password ""                            // Access to your server to change stuff remotely or ingame. (Empty = disabled)
set g_password ""                               // Password Protected Server. Leave blank if you want players to join or set password if you want to keep public out.
set g_deadChat "0"                              // Toggle allowing dead players to chat with living players. (0 (default) or 1)
set g_inactivity "420"                          // Time in seconds before the server will kick a user for inactivity. (range 0 - 10000)
set sv_kickBanTime "3600"                       // Time in seconds for a player temporary ban. (on kick/tempban) (range 0 - 3600)
set sv_allowClientConsole "1"                   // Enable or Disable players ability to access server commands.
set sv_timeout "20"                             // Timeout time period. You will timeout after (20) seconds when attempting to connect or if you are getting connection interruptions.
set sv_reconnectlimit "3"                       // How many times you can try to reconnect.



//////////////////////////////////////////////////
// BASE GAME CONFIGURATION                      //
//////////////////////////////////////////////////
//                                              //
// blitz - Blitz                                //
// conf - Kill Confirmed                        //
// cranked - Cranked                            //
// dm - Free-for-all                            //
// dom - Domination                             //
// grind - Grind                                //
// grnd - Drop Zone                             //
// gun - Gun Game                               //
// horde - Safeguard                            //
// infect - Infected                            //
// sd - Search and Destroy                      //
// siege - Reinforce                            //
// sotf - Hunted                                //
// sotf_ffa - Hunted FFA                        //
// sr - Search and Rescue                       //
// war - Team Deathmatch                        //
//                                              //
//////////////////////////////////////////////////

//GAMETYPE CURRENTLY HAS TO BE SET VIA THE MAP ROTATION

set scr_game_allowkillcam "1"                   // Allow Killcam.
set team_rebalance "1"                          // Auto Balance teams?
set scr_teambalance "1"                         // Enable or Disable auto balance.
set scr_game_spectatetype "2"                   // Allow Spectators. 0 Disabled, 1 Team/Player only, 2 Free
set sv_checkMinPlayers "0"
set scr_game_graceperiod "0"
set scr_game_onlyheadshots "0"
set scr_game_deathpointloss "0"
set scr_game_suicidepointloss "0"
set scr_team_teamkillpointloss "1"
set scr_game_perks "1"
set scr_game_forceuav "0"
set scr_game_hardpoints "1"
set scr_nukeTimer "10"
set scr_nukeCancelMode "0"
set scr_default_maxagents "5"
set scr_disableClientSpawnTraces "0"
set scr_hardpoint_allowartillery "1"
set scr_hardpoint_allowuav "1"
set scr_hardpoint_allowhelicopter "1"
set scr_team_respawntime "0"
set scr_player_numlives	"0"
set scr_player_respawndelay "0"
set scr_player_suicidespawndelay "0"
set scr_player_forcerespawn "1"
set scr_player_sprinttime "4"
set scr_explBulletMod "1"
set scr_maxPerPlayerExplosives "2"

//////////////////////////////////////////////////
// HARDCORE CONFIGURATION                       //
//////////////////////////////////////////////////
// uncomment below commands for some hardcore	//
// by removing the // before each set dvar.     //
//////////////////////////////////////////////////

// set g_hardcore "0"                           // Enable hardcore mode.
// set scr_hardcore "0"                         // Enable hardcore mode again...
// set ui_hud_hardcore "0"                      // Removes Heads up display which can be used both regular and HC.
// set scr_player_maxhealth "100"                // Percent of Health players will have on Respawn. (100 is normal. 30 is hardcore)
// set scr_team_fftype "0"                      // Enable or Disable Friendly Fire. (1 on, 2 reflect, 3 shared)
// set scr_player_healthregentime "5"           // Time it takes you to recover damage. (5 is normal, 0 is hardcore)
// set scr_team_teamkillspawndelay "20"
// set scr_team_kickteamkillers "0"

//////////////////////////////////////////////////
// TEAM DEATHMATCH GAMETYPE SETTINGS            //
//////////////////////////////////////////////////

set scr_war_scorelimit "75"                     // Score limit to win the game.
set scr_war_timelimit "10"                      // Duration in minutes for the game to end if the score limit isn't reached.
set scr_war_playerrespawndelay "0"              // How long player will wait until respawn.
set scr_war_waverespawndelay "0"                // Duration is seconds before the first respawn in each round.
set scr_war_numlives "0"                        // Number of lives per player 0 for unlimited.
set scr_war_roundlimit "1"                      // Rounds per game.
set scr_war_winlimit "1"                        // Amount of wins needed to win a round-based game
set scr_war_promode "0" 

//////////////////////////////////////////////////
// FREE FOR ALL GAMETYPE SETTINGS               //
//////////////////////////////////////////////////

set scr_dm_scorelimit "30"                      // Score limit to win the game.
set scr_dm_timelimit "10"                       // Duration in minutes for the game to end if the score limit isn't reached.
set scr_dm_playerrespawndelay "0"               // How long player will wait until respawn.
set scr_dm_numlives "0"                         // Number of lives per player. 0 for unlimited.
set scr_dm_roundlimit "1"                       // Rounds per game.
set scr_dm_winlimit "1"                         // Amount of wins needed to win a round-based game.
set scr_dm_promode "0" 

//////////////////////////////////////////////////
// DOMINATION GAMETYPE SETTINGS                 //
//////////////////////////////////////////////////

set scr_dom_scorelimit "200"                    // Score limit to win the game.
set scr_dom_timelimit "0"                       // Duration in minutes for the game to end if the score limit isn't reached.
set scr_dom_playerrespawndelay "0"              // How long player will wait until respawn.
set scr_dom_waverespawndelay "0"                // Duration is seconds before the first respawn in each round.
set scr_dom_numlives "0"                        // Number of lives per player per game. 0 is unlimited.
set scr_dom_roundlimit "1"                      // Rounds per game.
set scr_dom_winlimit "1"                        // Amount of wins needed to win a round-based game.
set scr_dom_promode "0"

//////////////////////////////////////////////////
// SEARCH AND DESTROY GAMETYPE SETTINGS         //
//////////////////////////////////////////////////

set scr_sd_scorelimit "1"                       // Score limit required to win the game.
set scr_sd_timelimit "2.5"                      // Duration in minutes for the game to end if the score limit isn't reached.
set scr_sd_playerrespawndelay "0"               // How long player will wait until respawn.
set scr_sd_waverespawndelay "0"                 // Duration is seconds before the first respawn in each round.
set scr_sd_numlives "1"                         // Number of lives per player per game.
set scr_sd_roundlimit "0"                       // Rounds the game is limited to 0 for unlimited.
set scr_sd_winlimit "4"                         // Amount of wins needed to win a round-based game.
set scr_sd_roundswitch "3"                      // After X rounds, switch sides.
set scr_sd_bombtimer "45"                       // Time taken for the bomb to detonate.
set scr_sd_defusetime "5"                       // Time taken to defuse the bomb.
set scr_sd_multibomb "0"                        // Allow multiple people to 'have the bomb'.
set scr_sd_planttime "5"                        // How long will it take player to 'plant the bomb'.
set scr_sd_promode "0"

//////////////////////////////////////////////////
// SEARCH AND RESCUE GAMETYPE SETTINGS          //
//////////////////////////////////////////////////

set scr_sr_scorelimit "1"                       // Score limit required to win the game.
set scr_sr_timelimit "2.5"                      // Duration in minutes for the game to end if the score limit isn't reached.
set scr_sr_playerrespawndelay "0"               // How long player will wait until respawn.
set scr_sr_waverespawndelay "0"                 // Duration is seconds before the first respawn in each round.
set scr_sr_numlives "1"                         // Number of lives per player per game.
set scr_sr_roundlimit "0"                       // Rounds the game is limited to 0 for unlimited.
set scr_sr_winlimit "4"                         // amount of wins needed to win a round-based game.
set scr_sr_roundswitch "3"                      // After X rounds, switch sides.
set scr_sr_bombtimer "45"                       // Time taken for the bomb to detonate.
set scr_sr_defusetime "5"                       // Time taken to defuse the bomb.
set scr_sr_multibomb "0"                        // allow multiple people to 'have the bomb'.
set scr_sr_planttime "5"                        // How long will it take player to 'plant the bomb'.
set scr_sr_promode "0"

//////////////////////////////////////////////////
// KILL CONFIRMED GAMETYPE SETTINGS             //
//////////////////////////////////////////////////

set scr_conf_scorelimit "65"                    // Score limit to win the game.
set scr_conf_timelimit "10"                     // Duration in minutes for the game to end if the score limit isn't reached.
set scr_conf_playerrespawndelay "0"             // How long player will wait until respawn.
set scr_conf_waverespawndelay "0"               // Duration is seconds before the first respawn in each round.
set scr_conf_numlives "0"                       // Number of lives per player 0 for unlimited.
set scr_conf_roundlimit "1"                     // Rounds per game.
set scr_conf_winlimit "1"                       // Amount of wins needed to win a round-based game.
set scr_conf_promode "0" 

//////////////////////////////////////////////////
// INFECTED DRAFT GAMETYPE SETTINGS             //
//////////////////////////////////////////////////

set scr_infect_timelimit "10"                   // Duration in minutes for the game to end if the score limit isn't reached.
set scr_infect_playerrespawndelay "0"           // How long player will wait until respawn.
set scr_infect_waverespawndelay "0"             // Duration is seconds before the first respawn in each round.
set scr_infect_numlives "0"                     // Number of lives per player 0 for unlimited.
set scr_infect_roundlimit "1"                   // Rounds per game.
set scr_infect_winlimit "1"                     // Amount of wins needed to win a round-based game.
set scr_infect_promode "0" 

//////////////////////////////////////////////////
// GRIND GAMETYPE SETTINGS                      //
//////////////////////////////////////////////////

set scr_grind_scorelimit "65"                   // Score limit to win the game.
set scr_grind_timelimit "10"                    // Duration in minutes for the game to end if the score limit isn't reached.
set scr_grind_playerrespawndelay "0"            // How long player will wait until respawn.
set scr_grind_waverespawndelay "0"              // Duration is seconds before the first respawn in each round.
set scr_grind_numlives "0"                      // Number of lives per player 0 for unlimited.
set scr_grind_roundlimit "1"                    // Rounds per game.
set scr_grind_winlimit "1"                      // Amount of wins needed to win a round-based game.
set scr_grind_promode "0" 

//////////////////////////////////////////////////
// DROP ZONE GAMETYPE SETTINGS                  //
//////////////////////////////////////////////////
                                                
set scr_grnd_scorelimit "7500"                  // Score limit to win the game.
set scr_grnd_timelimit "10"                     // Duration in minutes for the game to end if the score limit isn't reached.
set scr_grnd_dropTime "15"                      // Time it takes for the care packages to drop.
set scr_grnd_numlives "0"                       // Number of lives per player 0 for unlimited.
set scr_grnd_playerrespawndelay "0"             // How long player will wait until respawn.
set scr_grnd_waverespawndelay "0"               // Duration is seconds before the first respawn in each round.
set scr_grnd_winlimit "1"                       // Amount of wins needed to win a round-based game.
set scr_grnd_zoneSwitchTime "60"                // Amount of time before the zone switches.
set scr_grnd_promode "0"

//////////////////////////////////////////////////
// BLITZ GAMETYPE SETTINGS                      //
//////////////////////////////////////////////////

set scr_blitz_scorelimit "16"                   // Score limit to win the game.
set scr_blitz_timelimit "5"                     // Duration in minutes for the game to end if the score limit isn't reached.
set scr_blitz_playerrespawndelay "0"            // How long player will wait until respawn.
set scr_blitz_waverespawndelay "0"              // Duration is seconds before the first respawn in each round.
set scr_blitz_numlives "0"                      // Number of lives per player 0 for unlimited.
set scr_blitz_roundlimit "2"                    // Rounds per game.
set scr_blitz_roundswitch "1"                   // Switching sides.
set scr_blitz_winlimit "1"                      // Amount of wins needed to win a round-based game.
set scr_blitz_scoredelay "10"
set scr_blitz_promode "0" 

//////////////////////////////////////////////////
// CRANKED GAMETYPE SETTINGS                    //
//////////////////////////////////////////////////

set scr_cranked_scorelimit "100"                // Score limit to win the game.
set scr_cranked_timelimit "10"                  // Duration in minutes for the game to end if the score limit isn't reached.
set scr_cranked_playerrespawndelay "0"          // How long player will wait until respawn.
set scr_cranked_waverespawndelay "0"            // Duration is seconds before the first respawn in each round.
set scr_cranked_numlives "0"                    // Number of lives per player 0 for unlimited.
set scr_cranked_roundlimit "1"                  // Rounds per game.
set scr_cranked_winlimit "1"                    // Amount of wins needed to win a round-based game.
set scr_cranked_teambased "1"                   // Cranked in Team mode instead of Free-for-all.
set scr_cranked_scorelimit_ffa "60"             // Score limit to win the game on FFA mode if teambased is set to 0.
set scr_cranked_promode "0" 

//////////////////////////////////////////////////
// SAFEGUARD GAMETYPE SETTINGS                  //
//////////////////////////////////////////////////

set scr_horde_scorelimit "0"                    // Score limit to win the game.
set scr_horde_timelimit "0"                     // Duration in minutes for the game to end if the score limit isn't reached.
set scr_horde_roundlimit "1"                    // Rounds per game.
set scr_horde_winlimit "1"                      // Amount of wins needed to win a round-based game.
set scr_horde_numlives "1"                      // Number of lives per player 0 for unlimited.
set scr_horde_playerrespawndelay "0"            // How long player will wait until respawn.
set scr_horde_waverespawndelay "0"              // Duration is seconds before the first respawn in each round.
set scr_horde_promode "0"
set scr_horde_maxagents	"24"
set scr_horde_difficulty "3"

//////////////////////////////////////////////////
// HUNTED GAMETYPE SETTINGS                     //
//////////////////////////////////////////////////

set scr_sotf_scorelimit	"65"                    // Score limit to win the game.
set scr_sotf_timelimit "10"                     // Duration in minutes for the game to end if the score limit isn't reached.
set scr_sotf_roundlimit	"1"                     // Rounds per game.
set scr_sotf_winlimit "1"                       // Amount of wins needed to win a round-based game.
set scr_sotf_numlives "0"                       // Number of lives per player 0 for unlimited.
set scr_sotf_playerrespawndelay	"0"             // How long player will wait until respawn.
set scr_sotf_waverespawndelay "0"               // Duration is seconds before the first respawn in each round.
set scr_sotf_promode "0"

//////////////////////////////////////////////////
// HUNTED (FFA) GAMETYPE SETTINGS               //
//////////////////////////////////////////////////

set scr_sotf_ffa_scorelimit "25"                // Score limit to win the game.
set scr_sotf_ffa_timelimit "10"                 // Duration in minutes for the game to end if the score limit isn't reached.
set scr_sotf_ffa_roundlimit "1"                 // Rounds per game.
set scr_sotf_ffa_winlimit "1"                   // Amount of wins needed to win a round-based game.
set scr_sotf_ffa_numlives "0"                   // Number of lives per player 0 for unlimited.
set scr_sotf_ffa_playerrespawndelay "0"         // How long player will wait until respawn.
set scr_sotf_ffa_waverespawndelay "0"           // Duration is seconds before the first respawn in each round.
set scr_sotf_ffa_promode "0"

////////////////////////////////////////////////////////
// MAP SHORT NAMES ROTATION LIST                      //
////////////////////////////////////////////////////////
//                                                    //
//  Breakout  - mp_parkour                                      
//  MayDay - mp_breakneck
//  Carnage (free) - mp_cranage2	
//  Grounded -   mp_desert
//  scortch - mp_divide
//  Genisis - mp_dome_iw
//  Throwback - mp_fallen
//  Frontier - mp_frontend
// precinct - mp_metropolis
//  crusher - mp_quarry
// renaissance (free) - mp_renaissance2
// Retaiation  - mp_riot
// Skydock - mp_rivet
// Terminal - mp_skyway
// Turista (Summer) - mp_turista2
// Permafrost (free) - mp_permafrost2
// Frost - mp_proto
//  Domination 
//  Neon (dlc) - mp_neon
//  noir (DLC) - mp_prime 
//  excess (DLC)- mp_flip
//  scrap  (DLC) - 
//  archive (DLC) - mp_mansion
//  ember (DLC) - mp_junk
//  fore
//  bermuda
// Heartland
// depot 22
// altitude 
		



set sv_maprotation "gametype dom map mp_breakneck" g_hardcore 0 +set xblive_privatematch 0

**Comment by hotdogwater69420** [comment]
im trying to set up a server for zombies but im unable to connnect using connect ip. when i press enter nothing happens. is there a port that i should have open/include at the end of the ip or am i not supposed to be connecting through my public ipv4 address. also where should the !start_zm_server.bat be.

**Comment by Koriebonx98** [comment]
Not that I’m aware of, again I’m not a dev or anything but have used the other mod clients similar that’s why I was able to use them files to set up a basic server. When I was doing it I was using the ipv4 adress and that seemed to work.

best solution can suggest is go to the other launchers and look at server hosting trouble shooting and most issues should work.

hoping some people use the code provided above to potentially set servers up,  and the possibly a way to have master servers in game

**Comment by hotdogwater69420** [comment]
i think my problem is port forwarding but idk which ports need to be forwarded for this server

**Comment by Koriebonx98** [comment]
> @Koriebonx98 could i work on this with you? i have a pssoiblle fix send me link to the files

I’m not a dev or anything 😩 I’ve used other mod clients simalr to this so this is universal stuff. But I’ve put the code up on here so you can use or remake for your own.

Any fixes, tweaks or changes that could help everyone feel free to explain and post

**Comment by Koriebonx98** [comment]
> i think my problem is port forwarding but idk which ports need to be forwarded for this server and which type

Yeah more than likely, I’m not too sure myself. But maybe make create a dedicated port and then try that. I’m sure there’s certain ports on the other cods so maybe the same

**Comment by hotdogwater69420** [comment]
even if it was a port forwarding issue i still dont know why i wouldnt be able to connect locally. you said you had it working right?

**Comment by Koriebonx98** [comment]
Partially but haven’t used mod for like 2 months so I would have to go back through make sure works with latest version ect. But one ox was ethernet and one was Wi-Fi, so maybe ethernet helps in some way?

**Comment by Koriebonx98** [comment]
I mainly had it set up just for the zombies, I had to wait for the bat scrip to be running first before I could use the connect command to join game

**Comment by hotdogwater69420** [comment]
i got it to work after port forwarding but now im having a problem where the server will crash after extended use. the error says "exceeded maximum number of script variables (children)".

**Comment by Koriebonx98** [comment]
I said partly working? I’ll go back through the files later but think files used are outdated

**Comment by Koriebonx98** [comment]
> i got it to work after port forwarding but now im having a problem where the server will crash after extended use. the error says "exceeded maximum number of script variables (children)".

Sorry only just seen this, I’m not too sure on this error maybe try reset network connections,
Revalidaed game
And try latest build?  Hopefully one of them will help

**Comment by Koriebonx98** [comment]
I’m Going to close this topic as I have another one about servers for people to look at, it includes files to hopefully work for everyone

**Comment by Koriebonx98** [comment]
I’m Going to close this topic as I have another one about servers for people to look at, it includes files to hopefully work for everyone
