### ISSUE TITLE
Why no precompiled .exe file?

### ISSUE THREAD

**Issue by Chyddo** [Joelrau/iw7-mod#64]
Hi lads, i am interrested in this client because i do not have faith in vanilla Infinite Warfare servers being 100% secure. Does this allow me to play zombies solo without connecting to their servers?

Anyway, is there any particular reason why there isn't a precompiled executable uploaded to your github? I am not very knowledgeable when it comes to programming and development of these projects, but i am interrested in testing it for sure.

Any response is appreciated, have a nice day <3
// Chy

**Comment by MattKlay** [comment]
I think it would be considered as a release. But, yeah a pre-compiled executable would be nice.

**Comment by herrblitzkrieg** [comment]
> I am not very knowledgeable when it comes to programming and development of these projects, but i am interrested in testing it for sure.

You can easily compile the client yourself with Visual Studio. The how-to already has been laid out before by others. See https://github.com/Joelrau/iw7-mod/issues/25#issuecomment-1427887477 and https://github.com/Joelrau/iw7-mod/issues/44 for reference.

**Comment by QuartzFox** [comment]
"easily" is a stretch, I've only been able to get this project to compile correctly once in the past, and am not able to compile the current version. There is no reason for there not to be a precompiled .exe available, especially when progress on this project is slow and there wouldn't be anything to get out of date for months at a time.

**Comment by Koriebonx98** [comment]
If someone could make a .exe file with the other files in a zip it would be more easier for some, but depends if someone’s willing to re do exe and upload every update

**Comment by mjkzy** [comment]
because this client isn't ready. we are still actively working and will report on further information. compile yourself if you can but plz open issues related to client only
