### ISSUE TITLE
how can i set up a server to play with a friend?

### ISSUE THREAD

**Issue by salvx** [Joelrau/iw7-mod#66]
somebody mentioned servers and i dont know how to set them up, i also cant seem to see a connect command in the console

**Comment by kafoute** [comment]
did you find the solution? because I have the same thing as you

**Comment by Koriebonx98** [comment]
You need the files,

one is the cfg file (sets up the server stuff needed, game rules ect)

The other one is to start the server. 

Once a server is made you can connect with the “connect ip xxxxxipv4.adressxx “ fill x with the acc adress tho.

It’s on my other post the video you copy paste into txt file and rename to the right extension and name it according. 

Server trouble shooting, your best bet is looking at the h1, h2, or plutonium files as it’s legit the same field and structure

**Comment by vos6434** [comment]
last time I've tried connecting the game didn't recognise the connect command. It didn't even show up in console autocompletion.

**Comment by Koriebonx98** [comment]
Try slash and then hit shift? You can always use the other console window for commands. It’s like a powershell interface

**Comment by Koriebonx98** [comment]
> last time I've tried connecting the game didn't recognise the connect command. It didn't even show up in console autocompletion.

I also realised I haven’t updated iw7 in a while so I’ll make a back up of it before I update. 
But try comply the latest iw7 and try the files I mention on the other post. Let me know if works but I don’t have great Wi-Fi or another account to try it on. 

So I was just hosting a private zombies game with map rotation on my pc, and then connecting to that server itself. I believe I was able to obtain xp
However you can’t access the shop, so I used the unlock all command

**Comment by Koriebonx98** [comment]
> last time I've tried connecting the game didn't recognise the connect command. It didn't even show up in console autocompletion.


1) You need a server to connect too 

2) if it’s zombies you need load up the zombies section and then use the command.

In the server command it’s either connect cp (zombies) or mp (multiplayer) if not on the right menu server won’t load
