### ISSUE TITLE
Owl Statue Bug.

### ISSUE THREAD

**Issue by OVQ2** [Joelrau/iw7-mod#67]
On the map Rave in the Redwoods, the Acid Rain weapon requires you place down an owl statue at the cabins. 

On the steam version this works as expected, on iw7-mod I tried in 2 separate games, but was unsuccessful in being able to place down the owl statue as the prompt did not appear.

This may need further testing, but I could not get it to work.

![image](https://github.com/Joelrau/iw7-mod/assets/115388762/65719149-1734-4927-89b6-c153da34959e)

**Comment by mjkzy** [comment]
sounds like we need to check the GSC, thanks for reporting

**Comment by mjkzy** [comment]
![image](https://github.com/Joelrau/iw7-mod/assets/64374267/68f5f7ac-472e-4319-94fc-649011f7cf72)
works for me
