### ISSUE TITLE
Some permanent upgrades could use a console command to unlock.

### ISSUE THREAD

**Issue by NolanHewitt** [Joelrau/iw7-mod#69]
The katana wallbuy on shaolin shuffle, and the chainsaw on rave in the redwoods can be permanently unlockable wallbuys after beating the maps easter eggs, a console command to unlock these easily would be a nice addition.

**Comment by mjkzy** [comment]
![image](https://github.com/Joelrau/iw7-mod/assets/64374267/bc278146-9f65-4804-b5d5-3ded6553fa8c)
seems to work after using `unlockstatsEE`
