### ISSUE TITLE
Command for online

### ISSUE THREAD

**Issue by Shling1** [Joelrau/iw7-mod#71]
Understand Online doesnt work, whats the command to join someone via ip

**Comment by monocolotion** [comment]
connect IP

**Comment by hotdogwater69420** [comment]
wouldnt you have to host a dedicated server for that since the mod doesnt have servers

**Comment by Koriebonx98** [comment]
Check out my post I have the codes to set up dedicated server. 
I basicly used the same set up as other mod clients for cod. 

But you can copy paste the code into a cfg file and the “!start.server” file to get working 

Zombie one should work as long as correct files,

multiplayer, there is way to get bots in the match but as of now they don’t function
