### ISSUE TITLE
Failed to verify ownership of the game

### ISSUE THREAD

**Issue by PengestMunch** [Joelrau/iw7-mod#73]
i have the game on steam however for some reason it says i dont have it, the files are in the right place everythings been done, i have it but it doesnt think i do? could somebody help me please

**Comment by Koriebonx98** [comment]
Try, re validate the game. Clear steam cache, delete mod files reinstall? 

Try using the same account that bought the game as the one logged into to steam when loading the mod client? 

Hopefully one of them will help resolve issue

**Comment by BoxOfMysteriez** [comment]
It seems like you have to have Steam open and online on the account you purchased the game on. This is how it works for me anyway. Hopefully in the future the check only has to be ran once that way the client can be played offline/without Steam

**Comment by mjkzy** [comment]
fixed, use `-nosteam` for offline usage
