### ISSUE TITLE
Character Feet Disappearing

### ISSUE THREAD

**Issue by Praveshan0710** [Joelrau/iw7-mod#76]
When you look down, you can see your own character's feet but, when you crouch, your feet disappear. In Campaign, you can see your feet even when you crouch.

**Comment by BoxOfMysteriez** [comment]
The legs seemed to be positioned differently in the MP portions of the game vs how they appear in singleplayer. On wider FOV's you can still seem them when moving around a bit. Unsure if this is how the original game behaved or just something with the client
