### ISSUE TITLE
Servers 

### ISSUE THREAD

**Issue by Koriebonx98** [Joelrau/iw7-mod#78]
for all those that was asking me to upload my files,

I have made a zip file on the archive.org so anyone can tweak and play around all they want

I've only got one steam account so I've not tested if works externally but for self use it should work

multiplayer bots don't work they are frozen until someone can make a work around

https://archive.org/details/iw-7-mod-setup

cong the maps you wish to use in the files, zombies i have map rotation on 2 maps atm

dlc can be found cabbini mod and works without iw7 mod

**Comment by hotdogwater69420** [comment]
does this version still have the too many variables error?

**Comment by Koriebonx98** [comment]
I didn’t come across that error myself, but again I’ve not updated iw7 so my version may be outdated. 

Try tweak the files above to the ass basic as you can and see if you can get it working with your version. If you do post the mod version used and any lines you chnagwd

**Comment by Koriebonx98** [comment]
Can confirm it works fine on my end, latest mod and all.

please make sure if you host a zombie server when trying to join make sure you load up the zombie section of the game first before trying the connect command else it won’t work 

levelling up on zombies works!!
Bounties doesn’t seem to for some reason

**Comment by hotdogwater69420** [comment]
it works fine for me as well its just playing on the server for over 45 mins it tends to crash from my experience.

**Comment by Koriebonx98** [comment]
*bounties does work,

“Earn 50000 cash
Attack of the thing”

playing via single player not via server

**Comment by Koriebonx98** [comment]
> it works fine for me as well its just playing on the server for over 45 mins it tends to crash from my experience.

Was that a hosted server for just you or you and your friend? I’m in able to try 2 diffrent computers but dedicated server for zombies seems to work.

1st computer:
I 5 3750k 
16 gb ram
1660 gpu
Ethernet only

<hosted server> 
Allowed me to host and connect to a server made on same computer. 

My other pc 
I5 9400
16gb ram
2060 
Wi-Fi only 

was able connect to dedicated server on other pc, though I don’t have another steam account with game to try, it did what a dedicated server would do. Unsure how multiple connections would affected it hopefully it’s some minor tweaks

**Comment by hotdogwater69420** [comment]
it was a server for me and two other friends maybe thats causing issues

**Comment by Koriebonx98** [comment]
> Each time I start the server, right after the server starts it doesn't load the server fully because it "failed to find sound lengths file sounddata/cp/cp_zmb.json".
> Is there any manual fix for this? I've already reinstalled the game like three times and I don't have a single clue what the issue could be.
> ![image](https://user-images.githubusercontent.com/86118046/260978184-5fe876d8-4cf1-40fb-b994-2f10901b6261.png)

I did see this error in my powershell screen to, but it seemed to still work regardless of the error, 

I think I closed it down and restated the server

**Comment by Koriebonx98** [comment]
> it was a server for me and two other friends maybe thats causing issues

Quite possibly, I was self hosting and connecting to my own server with no one else, so could be a network problem.

have you tried using ethernet over Wi-Fi instead?? Might work better.

if not and you have a crappy lil comp, host server on that hooked with ethernet cable and server should be more stable

**Comment by Koriebonx98** [comment]
> Each time I start the server, right after the server starts it doesn't load the server fully because it "failed to find sound lengths file sounddata/cp/cp_zmb.json".
> Is there any manual fix for this? I've already reinstalled the game like three times and I don't have a single clue what the issue could be.
> ![image](https://user-images.githubusercontent.com/86118046/260978184-5fe876d8-4cf1-40fb-b994-2f10901b6261.png)

Did u try connecting dispite the error? 
I bleive it’s a iw7 end problem.
But when I play via server, sound works still displays this message

**Comment by Joelrau** [comment]
[sounddata.zip](https://github.com/Joelrau/iw7-mod/files/12359920/sounddata.zip)
the dedicated needs these sounddata files for some sounds like zombie music.

**Comment by DOOMSH0P** [comment]
> > Each time I start the server, right after the server starts it doesn't load the server fully because it "failed to find sound lengths file sounddata/cp/cp_zmb.json".
> > Is there any manual fix for this? I've already reinstalled the game like three times and I don't have a single clue what the issue could be.
> > ![image](https://user-images.githubusercontent.com/86118046/260978184-5fe876d8-4cf1-40fb-b994-2f10901b6261.png)
> 
> Did u try connecting dispite the error? I bleive it’s a iw7 end problem. But when I play via server, sound works still displays this message

Yeah. Tells me the server isn't open/it's closed. I reinstalled again, gonna try the sounddata.zip fix.

**Comment by DOOMSH0P** [comment]
> [sounddata.zip](https://github.com/Joelrau/iw7-mod/files/12359920/sounddata.zip) the dedicated needs these sounddata files for some sounds like zombie music.

Drag and drop into main folder or something specific?

**Comment by hotdogwater69420** [comment]
> > it was a server for me and two other friends maybe thats causing issues
> 
> Quite possibly, I was self hosting and connecting to my own server with no one else, so could be a network problem.
> 
> have you tried using ethernet over Wi-Fi instead?? Might work better.
> 
> if not and you have a crappy lil comp, host server on that hooked with ethernet cable and server should be more stable

its not a connection/hardware issue the server crashing with an error saying theres too many variables

**Comment by DOOMSH0P** [comment]
> Each time I start the server, right after the server starts it doesn't load the server fully because it "failed to find sound lengths file sounddata/cp/cp_zmb.json". Is there any manual fix for this? I've already reinstalled the game like three times and I don't have a single clue what the issue could be. ![image](https://user-images.githubusercontent.com/86118046/260978184-5fe876d8-4cf1-40fb-b994-2f10901b6261.png)

Fixed this error by using the sounddata.zip provided by Joelrau,

But now the server refuses to run(?)
![image](https://github.com/Joelrau/iw7-mod/assets/86118046/8a8b655d-3c5d-4598-9b83-4dab1ead60e0)

**Comment by Koriebonx98** [comment]
> > > it was a server for me and two other friends maybe thats causing issues
> > 
> > 
> > Quite possibly, I was self hosting and connecting to my own server with no one else, so could be a network problem.
> > have you tried using ethernet over Wi-Fi instead?? Might work better.
> > if not and you have a crappy lil comp, host server on that hooked with ethernet cable and server should be more stable
> 
> its not a connection/hardware issue the server crashing with an error saying theres too many variables

I’m not too sure then, deffo try ethernet over Wi-Fi though from personal experience.
If not it might be a iw7 bug

**Comment by Koriebonx98** [comment]
> > Each time I start the server, right after the server starts it doesn't load the server fully because it "failed to find sound lengths file sounddata/cp/cp_zmb.json". Is there any manual fix for this? I've already reinstalled the game like three times and I don't have a single clue what the issue could be. ![image](https://user-images.githubusercontent.com/86118046/260978184-5fe876d8-4cf1-40fb-b994-2f10901b6261.png)
> 
> Fixed this error by using the sounddata.zip provided by Joelrau,
> 
> But now the server refuses to run(?). Seems like it gets stuck at loading "cp_zmb" no matter how long I leave it running, never seems to get past. Running on a freshly reinstalled version of IW from Steam w/ no DLCs as well. ![image](https://user-images.githubusercontent.com/86118046/261192353-8a8b655d-3c5d-4598-9b83-4dab1ead60e0.png)

Try download the dlc it could help stop the problem maybe, any isssue Google iw7 dlc codcabbin mod site. And it’ll come up with the zombie dlc, <that’s where got mine from\\ also works on steam even if not purchased> 🤷🏻‍♂️🤷🏻‍♂️

**Comment by Zeddiy** [comment]
What are you supposed to do after connecting connecting to the ip is the game supposed to take you straight into their lobby or do you have to type something else out before joining the lobby

**Comment by Koriebonx98** [comment]
> What are you supposed to do after connecting to the ip is the game supposed to take you straight into their lobby or do you have to type something else out before joining the lobby

Not sure about lobbies, but you set up a server use the above files. When say zombie server is running and have to be in the zombies menu before enter the connect command, this should allow multiplayer with friends

**Comment by 0ptimusX** [comment]
This is indeed very similar to hosting a server for IW6, S1, etc. It just needs a server browser, perhaps with Lua/LUI support. This can be possible, just like with IW6, S1, etc. As for the master server, we can either host our own or Quak could consider merging with AlterWare and using their master server, etc.

**Comment by Ston3Cold** [comment]
It's a pity that this client is in limbo / being ignored. I'm know where not entitled to any updates, but the majority of the work has been done. If gsc support was added I believe we should be set to fill in the remaining gaps.

**Comment by Koriebonx98** [comment]
> This is indeed very similar to hosting a server for IW6, S1, etc. It just needs a server browser, perhaps with Lua/LUI support. This can be possible, just like with IW6, S1, etc. As for the master server, we can either host our own or Quak could consider merging with AlterWare and using their master server, etc.

Legit if you go through the files I provided you may see some references to s1x mod as I did copy paste and change different settings such as map names but yeah it’s legit exactly he same thing as the other mods

**Comment by Koriebonx98** [comment]
> It's a pity that this client is in limbo / being ignored. I'm know where not entitled to any updates, but the majority of the work has been done. If gsc support was added I believe we should be set to fill in the remaining gaps.

That would be amazing if that could happen, then we can make this client alive for people who like this version of cod. Out of curiosity why not add Iw7x to plutonium? This would make it easier to play with set friends and have a forms system too? 

Just would be good to have a the same security measures in place, and an easier way of connecting to games

**Comment by Zeddiy** [comment]
im made a post about it lol and Koriebonx answered it already lol

**Comment by Koriebonx98** [comment]
> im made a post about it and Koriebonx answered it already lol

just doing what I can, if I answered your post please close it so others can find open post easier.
I also set up a new one about servers so please read that one, hope it helps
