### ISSUE TITLE
Dedicated servers 

### ISSUE THREAD

**Issue by Nashar101** [Joelrau/iw7-mod#79]
is there a way to host a server on this mod to allow other people to join ?

**Comment by hotdogwater69420** [comment]
theres an open thread titled "servers" that explains how to do it but the server always crashes after playing for an extended period of time

**Comment by Koriebonx98** [comment]
It was me that uploaded the files. 
Maybe using a lower version ow iw7 might resolve?

opening your nat might help?

try port forwarding? 

and make sure you use your ipv4 address with the “connect <ipv4 address>” 

any other server walk arounds look on the plutonium.pw forms, iw4, iw6, s1, h1 ect as it’s all the same

**Comment by mjkzy** [comment]
client is not finished and may have issues. at this time, we're not going to specific issues until client is at a decent point. thanks for understanding
