### ISSUE TITLE
Connecting to server

### ISSUE THREAD

**Issue by Zeddiy** [Joelrau/iw7-mod#85]
i was reading the read me and it says I need put my ipv4 (I know what ipv4 is) into zombies.bat. How do I put my ipv4 into Zombies.bat.

How does my friend join me after typing "connect ip" is he supposed to get put into my lobby or how does he join after connecting?

**Comment by Koriebonx98** [comment]
You click taskbar, then find network and it should be there

**Comment by Koriebonx98** [comment]
If server is multiplayer than he has to load multiplayer before connecting to your multiplayer server same as zombies. Guessing you’ve never used similar mod clients?

**Comment by Zeddiy** [comment]
No I haven’t but me and my friend figured out all we did we used radmin vpn and started the server there

**Comment by Zeddiy** [comment]
For Us idk why but it didnt work until we used radmin vpn and your server files before that it just straight up wouldnt do anything when we entered connect (ip)

**Comment by Koriebonx98** [comment]
> For Us idk why but it didnt work until we used radmin vpn before that it just straight up wouldnt do anything when we entered connect (ip).

Possibly a bug, hopefully gets sorted
