### ISSUE TITLE
AI difficulty command do not work

### ISSUE THREAD

**Issue by TheNineBreaker** [Joelrau/iw7-mod#87]
Every time i use the "bot_difficultydefault" command when match loads it seems to not affect anything. Be it "0", "1" or "2" AI always play like it set on max difficulty. Tried to type it before the match, during match, in the same line with commands that start a match. It shows the correct number in console and bots ranks is low, but they always play like on max difficulty level. Not really sure what this is. Maybe there is a fix or its actually a bug.

**Comment by Koriebonx98** [comment]
Possibly a bug as bots tend to work offline, servers are more iffy
