### ISSUE TITLE
Minidump error

### ISSUE THREAD

**Issue by MrDeathFox** [Joelrau/iw7-mod#88]
I'm tryna play zombies and do easter eggs or high rounds and can't get above scene 5-9 without it crashing. Any fixes?
![image_2023-09-21_212314628](https://github.com/Joelrau/iw7-mod/assets/91103691/b5985c52-b18d-4e91-ad3e-9818e4447c10)

**Comment by Koriebonx98** [comment]
Re validate your files, downlaod latest version of iw7 and re try? 
worst comes uninstall game and reinstall it

**Comment by mjkzy** [comment]
old issue, reopen if still happening
