### ISSUE TITLE
Servers #2

### ISSUE THREAD

**Issue by Koriebonx98** [Joelrau/iw7-mod#90]
Since my previous post about servers and how to make them, I was wondering what everyone’s experience has been like? 
I only ask as I have one copy of iw7 and can host my own personal server but haven’t attempted to see if others are able to  connect due to having 1 copy. 

From my experience 
Zombies = 100 working as it should inc map rotation and contracts seem to work.

multiplayer = semi functional, extra commands on start up is needed and needs more work done to it. 
Map rotation works, bot function needs more work done to it.
 To get bots working need to add extra commands on start up, have a team selected or have ffa game mode.

would be great once that’s fixed to have a server browser for lan, online ect. And then we can have dedicated servers up and available.

if anyone has any updated server files, fixes or work arounds feel free to share.

make sure to use latest update of iw7, and own the game in steam 

and if anyone wants to host any dedicated servers 
Where others can join, please add a comment with the ip, the type of mode, e.g zombies, the maps used and any scripts that you have added that others need to join. For security reasons If you have it password protected (recommended) please ensure a safe way for people to have the password to connect, e.g direct message or adding as steam friend and pm them that way.

for example (this what the comment  should look like)

Server name: Koriebonx98 iw7 zombies
Ip: 321.243.0.0
Mode: Zombies, 
Dlc: yes/no
Maps: “all” “single” “couple” (space land, radioactive, cabin ect)
Scripts: none required or “download link”
Password: “no” or “yes” (contact via steam/redit)
Steam name: Koriebonx98 
Social: Reddit, discord ect

**Comment by Koriebonx98** [comment]
If anyone wants to make there own batch file to load up iw7 mod to that specific server on launch 
Add this to a clear .bat file

Iw7-mod.exe -cpMode xxx.xxx.x.x 

replace x’s with the ipv4 address, when you click on the bat file it’ll load up and connect to the server

**Comment by aquaragon** [comment]
Can I add you on discord to ask how you got this config setup?

**Comment by Koriebonx98** [comment]
> Can I add you on discord to ask how you got this config setup?

I don’t have discord, but here’s the post I done on how to set up 

https://github.com/Joelrau/iw7-mod/issues/78

**Comment by aquaragon** [comment]
Ok thank you, do you know what port the server runs on?

**Comment by Koriebonx98** [comment]
Umm any, I believe. I just copied the iw6/sx1 server config and changed the main stuff, so possibly whatever one they was using. But I’m sure it’s already in the config files I’ve uploaded

**Comment by Apothesised** [comment]
hey, ive been trying to set up a server for me and a friend, and ive no idea how to host a server or confirm one is working. id love a walkthrough of how you set yours up

**Comment by Koriebonx98** [comment]
> hey, ive been trying to set up a server for me and a friend, and ive no idea how to host a server or confirm one is working. id love a walkthrough of how you set yours up

Try the link above, it has the files needed to host a server. 
just downland them and place on root of game.
You’d have to edit it for your likings (I’ll update it with map names) 

Zombies work as should, haven’t tried 2x copies yet but self hosting works for me 

multiplayer: semi working with bots (needs scripting to work) but map rotation and other stuff should work

**Comment by aquaragon** [comment]
nevermind I figured it out, thank you so much for the help

**Comment by Koriebonx98** [comment]
> nevermind I figured it out, thank you so much for the help

It’s okay can you please explain what you did to get port working? It would be helpful to others hopefully the community can make servers and the dev make the master server if they can see we got zombie servers working!

hopefuly multiplayer with bits gets fixed too!

**Comment by aquaragon** [comment]
I didn't get port working. I just used radmin VPN and allowed the application through the radmin firewall and my friend could join with the radmin IP.

**Comment by Koriebonx98** [comment]
> I didn't get port working. I just used radmin VPN and allowed the application through the radmin firewall and my friend could join with the radmin IP.

Okay thank you, hopefully the devs can tinker with this and make a way to add ports for servers and then I’d say we’re 80% done on the server’s part as of now
