### ISSUE TITLE
erros while building

### ISSUE THREAD

**Issue by ReaperWiiPlaza** [Joelrau/iw7-mod#91]
getting these errors when building in visual studio. Ive done git clone and everything else in the tutorial video.
![Screenshot 2023-10-20 055926](https://github.com/Joelrau/iw7-mod/assets/148541948/c7d064e9-b9dd-4d46-abe1-e26b98604995)

**Comment by Koriebonx98** [comment]
Some people been struggling with this, out of curiosity how many would benefit from a premade exe and file?

**Comment by NolanHewitt** [comment]
Many would benefit. I know multiple people interested in this who dont have the technical knowledge required to compile it themselves

**Comment by Koriebonx98** [comment]
> Many would benefit. I know multiple people interested in this who dont have the technical knowledge required to compile it themselves

I’ll try to make a archive.org link as I’m not use to GitHub atm. 
I’ll try update as often as can,
I have a link for the server files on there but I’ll try update all
