### ISSUE TITLE
Servers #3 

### ISSUE THREAD

**Issue by Koriebonx98** [Joelrau/iw7-mod#93]
Hi guys just a update to the server stuff I’ve been attempting to do for you all.

firstly I did have to use a custom version of iw7-mod that bypassed steam check as I own 1 copy but multiple pc’s (sorry devs) 

from my findings this is my conclusion until devs update mod further 

zombies mode:
1) All 4 maps working, need the “soundfile.zip” to host server to avoid the sound error that displayed without it.

2) it took a little while to connect after zombies in spaceland It did crash, after entering the connect command when match ended, re entering the connect <ipv4 adress> It loaded up the next map perfectly, same as the others without disconnecting.

3) contracts worked on the one pc but not the other.. not sure if a bug or if I should delete player folder and retry it that way?

Multiplayer: 

1) clients connects to same server no issue,

2) bots will not spawn at all, (mod needs to fix this issue or have a solution ti bypass) 

3) hosting a “lobby” crashes but using a server doesn’t crash. Prob the dev needs to fix some issues.

Other than that we are basically there now towards the servers, just depends when the devs fix some stuff to allow us this.

*fix bots not spawning 
*ability to make a lobby 
*server browser (even if bots don’t work but general connections do)

**Comment by belloumi-hamza** [comment]
hi koriebons. i tried everything you did to get server host working but its just not. can we talk on discord? my username on discord is kokolofo

**Comment by Koriebonx98** [comment]
> hi koriebons. i tried everything you did to get server host working but its just not. can we talk on discord? my username on discord is kokolofo

hi im afraid i dont have discord, 
since going back through the servers myself multiplayer can only be done (inc bots) via private match, until lua or other sort of scripting is supported.

other cod clients have a script as basic as 
"min players =1,ranked match = 1, on player spawn, spawn bots max, asign to team, team balance, start match" 

not as simple as that but give or take its the steps the scripts use to spawn bots & level up but acc scripted.

for now, 
go private match, make the game set up how you wish 
if team based, select team first with bumpers on controller, 
if want bots set that up too

then type (i belive its)
"xpartygo; xblive_privatematch 0" 

it should then load up ranked match but need to enter command each time

when playing team based games for some reason all bots inc friendly are enemies to the player so will lock onto any
game modes such as tdm, infected.

Zombies: all functional and working as it should, map rotation works the soundsfiles.zip in a prev post will sort the sound errors out
