### ISSUE TITLE
multiplayer bots {Script/scripts} 

### ISSUE THREAD

**Issue by Koriebonx98** [Joelrau/iw7-mod#94]
im grateful for all the hard work thats been put into this project, got zombie servers working and multiplayer without bots

is there anyway to make a small script that will add bots to multiplayer games and level up? this will then make the servers 100% done and then we would need a built in server browser to be fully functional 

server set up guide is avalible by me in the issues if you wish to remake into the default mod files for everyone

**Comment by Koriebonx98** [comment]
i have copied the ghost server stuff such as "auto bots" its a similar file of iw6 and sx1, if it works ill remake the server files for iw7-mod inc this so we can get servers up and running!! ill update when game loads

**Comment by Koriebonx98** [comment]
> i have copied the ghost server stuff such as "auto bots" its a similar file of iw6 and sx1, if it works ill remake the server files for iw7-mod inc this so we can get servers up and running!! ill update when game loads

couldnt get it working

map rotation for mp not working like other cod clients
no command for bots to spawn via cmd line so a script would be more beneifcal if someone can find away

only thing got working was "map <mp_name>" 

no cmd for game mode so it would default to tdm aka war 
i did try to change to ffa via cmd but didnt work

can spawn bots from private match using the "xpartygo;"  but thats as good as it gets
in private match your able to change game settings as it doesnt work via cmd yet

i also bought the season pass so i am able to fill in the rest of the mp maps

**Comment by Ston3Cold** [comment]
I can spawn bots on my dedicated server in private match mode, trying to join it however ,causes one to be kicked. I'm afraid that A LOT of effort is required to fix the client in its current state to allow:

Client to join- kick a bot from server
Allow client to be assigned to a team (but this stems from issue above)
Make the server ranked with bots
Allow gamemode to be set with g_gametype as it defaults to tdm every.single.time.

Sounds simple enough, but yeah, we won't get anywhere without these issues being addressed first I'm afraid.

**Comment by Koriebonx98** [comment]
How did you get bots to spawn on your dedi? 
or is this your own client?

so what i like to do is have a small windows 10 spare Pc be the server host running the server and then have another pc (mine) connect to the server.

If any sort of scripting was supported like previous cod clients I’m sure what I tried to do would have or could then work and do what your saying but on player spawn it then spawn bots. While still allowing levelling and progression. 

So far our best bet is a mp server without bits but means you need at least 8/10 players min for it or be semi decent but ideally it shouldn’t kick no one.

hope the dev comes across this and adds some support so we can progress, I’m not even a dev myself and the files I’ve provided to run the zombie server I’ve found on steam underground site so it’s partially working and people are aware so that’s a good step.

next step is to learn coding ect witch will take me years :/

**Comment by Ston3Cold** [comment]
Not my own client, I used this one :)

Not a coder either, but alas we can only hope. Well, iirc, I made sure that bot_AutoConnectDefault is set to 1. Then I executed xboxlive_privatematch 1. After that I simply then reloaded a map.

You could try map_restart (I think thats the cmd) after you execute those commands. Or you acn "string" them together with ; like this:

xboxlive_privatematch 1;map_restart or simply just load a map again, like "map mp_frontline".

You will need to play around with those cmds, its  combination of those. Bot_AutoConnectDefault always adds 17 bots. There is no cmd that you can use otherwise to spawn only 11 or 8, it always fills up the server. If you could kick a bot, or manage to find a cmd to kick, then yes, you could potentially join, but I've yet to discover the right cmd.

Anyhow, thats more or less my discovery to date :)

**Comment by Koriebonx98** [comment]
> Not my own client, I used this one :)
> 
> Not a coder either, but alas we can only hope. Well, iirc, I made sure that bot_AutoConnectDefault is set to 1. Then I executed xboxlive_privatematch 1. After that I simply then reloaded a map.
> 
> You could try map_restart (I think thats the cmd) after you execute those commands. Or you acn "string" them together with ; like this:
> 
> xboxlive_privatematch 1;map_restart or simply just load a map again, like "map mp_frontline".
> 
> You will need to play around with those cmds, its combination of those. Bot_AutoConnectDefault always adds 17 bots. There is no cmd that you can use otherwise to spawn only 11 or 8, it always fills up the server. If you could kick a bot, or manage to find a cmd to kick, then yes, you could potentially join, but I've yet to discover the right cmd.
> 
> Forgot to add, you can use the "status" cmd to check and verify if bots have connected to your dedi.
> 
> Anyhow, thats more or less my discovery to date :)

Your a life saver, I’ll deffo have a little look into this myself.

I also have been playing with other mod clients, with the boiii client in live “t7x” it’s called now, there’s a server browser right, and if you click on any server and add to “favourites” in the player folder it’ll create a “favourite_severs.txt” file with the ip of set server. 
if you edit and add your ipv4:port to it then your own server comes up in the favourites section, 

this would be good if iw7 supported it too, and allowed a “friends.txt” or a “friend_servers.txt” 

Friends.txt
Have it either be “ipv4”or “<name>:ipv4:port” or steamid or something like that, 
This would then make it easy joining matches/friends matches

friend_servers.txt
IPv4:port 
E.g “182.654.777:15710”

**Comment by Koriebonx98** [comment]
Forgot to mention in boiii new client where you add ip to the favourite server,

i added my own ip & port that’s used to host servers by default 1750 or something like that 

when not hosting a server but in the server browser it would display “koriebonx98” as the server (same as my user name, it was using user name as “server name”) 

so I added my other pc’s ip to the file, and had the username on the profile as “koriebonx98_2” this showed my other account in the server browser and said i was at the menu, when on “koriebonx98” and I then make a private match, it’ll show on the other pc that’s on the server browser what map I’m on, when I’m in the map loaded up and the “koriebonx98_2” account clicks “join” it then loads onto my game,

 but if I’ve not loaded up the map and “koriebonx_2” joins then it won’t connect & display error, only works when map is loaded, can always then do “map_restart” to then restart the map or run the “map_rotate”
Command
